/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTL_mathquiz;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class OneP extends javax.swing.JFrame {
    ArrayList<Quiz> li = Main.listQuiz;
    ArrayList<Integer> twenty_questionid = new ArrayList<Integer>();
    Random rd = new Random();
    public static int vitriCauHientai = 0;
        // Timer
        static int interval;
        static Timer timer;  
    Quiz nowQuiz;
    public OneP() {
        initComponents();
        init_20RandomQuestion();
        auto_loadQuestion(vitriCauHientai);
    }
    
    private void init_20RandomQuestion(){
        // load 20 cau bat ky
        while(twenty_questionid.size() < 20){
            int newRandomNumber = rd.nextInt(Main.listQuiz.size()-1) + 1;
            if(!twenty_questionid.contains(newRandomNumber)){
                twenty_questionid.add(newRandomNumber);
            }
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        traLoi_Btn = new javax.swing.JButton();
        cauthu_lbl = new javax.swing.JLabel();
        jLabel_Cauhoi = new javax.swing.JLabel();
        lbl_Answer_X = new javax.swing.JLabel();
        lbl_Answer_Y = new javax.swing.JLabel();
        lbl_Answer_Z = new javax.swing.JLabel();
        TextField_Answer_X = new javax.swing.JTextField();
        TextField_Answer_Y = new javax.swing.JTextField();
        TextField_Answer_Z = new javax.swing.JTextField();
        lbl_Score = new javax.swing.JLabel();
        lbl_CountScore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_CountTime = new javax.swing.JLabel();
        lbl_IDcauhoi = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        traLoi_Btn.setText("TraLoi");
        traLoi_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traLoi_BtnActionPerformed(evt);
            }
        });

        cauthu_lbl.setText("Câu hỏi số:");

        jLabel_Cauhoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Cauhoi.setText("j");

        lbl_Answer_X.setText("X");

        lbl_Answer_Y.setText("Y");

        lbl_Answer_Z.setText("Z");

        TextField_Answer_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Answer_XActionPerformed(evt);
            }
        });

        lbl_Score.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Score.setText("Điểm");

        lbl_CountScore.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_CountScore.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Thời gian còn lại");

        lbl_CountTime.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lbl_IDcauhoi.setText("id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cauthu_lbl)
                            .addComponent(lbl_IDcauhoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Cauhoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(traLoi_Btn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(183, 183, 183)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addComponent(lbl_CountTime, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(lbl_Score)
                                        .addGap(90, 90, 90))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_CountScore, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_Answer_Z, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                    .addComponent(lbl_Answer_Y, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Answer_X, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_Answer_Y)
                                    .addComponent(TextField_Answer_Z)
                                    .addComponent(TextField_Answer_X, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Cauhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cauthu_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_IDcauhoi)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Answer_X)
                    .addComponent(TextField_Answer_X))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Score)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CountTime, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CountScore, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Answer_Y)
                            .addComponent(TextField_Answer_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Answer_Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Answer_Z))
                        .addGap(18, 18, 18)
                        .addComponent(traLoi_Btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Auto-load cau hỏi
        private void auto_loadQuestion(int cauThuBaonhieu){
            cauthu_lbl.setText("Câu hỏi số " + (vitriCauHientai+1) + ":");
            nowQuiz = li.get(twenty_questionid.get(cauThuBaonhieu)-1);
            String s = nowQuiz.getQuiz();
            jLabel_Cauhoi.setText(convertToMultiline(s));
            lbl_Answer_X.setVisible(true);TextField_Answer_X.setVisible(true);TextField_Answer_X.setText("");
            lbl_Answer_Y.setVisible(true);TextField_Answer_Y.setVisible(true);TextField_Answer_Y.setText("");
            lbl_Answer_Z.setVisible(true);TextField_Answer_Z.setVisible(true);TextField_Answer_Z.setText("");
            lbl_IDcauhoi.setText(Integer.toString(nowQuiz.getId()));
            if(nowQuiz.getY().isEmpty()){
                lbl_Answer_Y.setVisible(false);    
                TextField_Answer_Y.setVisible(false);
            }
            if(nowQuiz.getZ().isEmpty()){
                lbl_Answer_Z.setVisible(false);
                TextField_Answer_Z.setVisible(false);
            }

            countdownTime();
    }

    // Đếm ngược thời gian
    private void countdownTime(){

        int delay = 1000;
        int period = 1000;
        timer = new Timer();
        interval = nowQuiz.time;
              timer.scheduleAtFixedRate(new TimerTask(){            
                public void run() {
                    lbl_CountTime.setText(Integer.toString(setInterval()));
                }

            }, delay, period);                       
    }    
    
    private final int setInterval() {
        if (interval == 1){
            soSanhKetqua();
            cauKetiep();                                     
        }
           
        return --interval;        
    }
    private void TextField_Answer_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Answer_XActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Answer_XActionPerformed

    private void traLoi_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traLoi_BtnActionPerformed
            // TODO add your handling code here:
            soSanhKetqua();
            cauKetiep();
    }//GEN-LAST:event_traLoi_BtnActionPerformed
    private void soSanhKetqua(){
             if(TextField_Answer_X.getText().equals(nowQuiz.x) && TextField_Answer_Y.getText().equals(nowQuiz.y) && TextField_Answer_Z.getText().equals(nowQuiz.z)){
                int diemHientai = Integer.parseInt(lbl_CountScore.getText());
                diemHientai += nowQuiz.getDiemCong();
                lbl_CountScore.setText(Integer.toString(diemHientai));
            }
            else{
                int diemHientai = Integer.parseInt(lbl_CountScore.getText());
                diemHientai -= nowQuiz.getDiemTru();
                if(diemHientai < 0){
                    diemHientai = 0;
                }
                lbl_CountScore.setText(Integer.toString(diemHientai));                
            }       
    }
    private void cauKetiep(){
        System.out.println(vitriCauHientai);
            if(vitriCauHientai < 19){
                timer.cancel();timer.purge();
                vitriCauHientai++;
                auto_loadQuestion(vitriCauHientai);                
            }
            else{
//                JOptionPane.showMessageDialog(rootPane, "Đã hoàn thành 20 câu hỏi");
                timer.cancel();timer.purge();
            }
    }
    public static String convertToMultiline(String orig)
    {
        return "<html>" + orig.replaceAll("\n", "<br>");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_Answer_X;
    private javax.swing.JTextField TextField_Answer_Y;
    private javax.swing.JTextField TextField_Answer_Z;
    private javax.swing.JLabel cauthu_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Cauhoi;
    private javax.swing.JLabel lbl_Answer_X;
    private javax.swing.JLabel lbl_Answer_Y;
    private javax.swing.JLabel lbl_Answer_Z;
    private javax.swing.JLabel lbl_CountScore;
    private javax.swing.JLabel lbl_CountTime;
    private javax.swing.JLabel lbl_IDcauhoi;
    private javax.swing.JLabel lbl_Score;
    private javax.swing.JButton traLoi_Btn;
    // End of variables declaration//GEN-END:variables
}
