/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTL_mathquiz;

import test_Package.QuizClient;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.JsonReader;
import javax.swing.JOptionPane;


/**
 *
 * @author My PC
 */
public class Main extends javax.swing.JFrame {
    public static ArrayList<Quiz> listQuiz = new ArrayList<>();


    /**
     * Creates new form Main
     */
    public Main() throws FileNotFoundException, IOException {
        InputStream inputStream = new FileInputStream("C:\\Users\\My PC\\Desktop\\exam-ltm-haimanhhonganh\\src\\quiz.json");
        JsonReader jsonReader = Json.createReader(inputStream);
        JsonArray arrJSON = jsonReader.readArray();      
        
        for (int i = 0; i < arrJSON.size(); i++) {
            JsonObject rootJSON = arrJSON.getJsonObject(i);
            Quiz quiz = new Quiz(rootJSON.getInt("id"), rootJSON.getInt("Dokho"),rootJSON.getString("Quiz"),rootJSON.getString("x"),rootJSON.getString("y"),rootJSON.getString("z"));

            listQuiz.add(quiz);
        }        
           
        
        jsonReader.close();
        inputStream.close();        
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        songsong_Btn = new javax.swing.JButton();
        Taketurn_Btn = new javax.swing.JButton();
        onePlayer_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        songsong_Btn.setText("Songsong");
        songsong_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songsong_BtnActionPerformed(evt);
            }
        });

        Taketurn_Btn.setText("TakeTurn");

        onePlayer_Btn.setText("Oneplayer");
        onePlayer_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onePlayer_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onePlayer_Btn)
                    .addComponent(Taketurn_Btn)
                    .addComponent(songsong_Btn))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(songsong_Btn)
                .addGap(18, 18, 18)
                .addComponent(Taketurn_Btn)
                .addGap(18, 18, 18)
                .addComponent(onePlayer_Btn)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onePlayer_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onePlayer_BtnActionPerformed
        

        OneP onep = new OneP();
        onep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_onePlayer_BtnActionPerformed

    private void songsong_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songsong_BtnActionPerformed
        // TODO add your handling code here:
        String user_name = JOptionPane.showInputDialog(null,"Nhap ten User:");
        
        QuizClient q = new QuizClient();
        q.run(user_name);
        
        OneP onep = new OneP();
        onep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_songsong_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Taketurn_Btn;
    private javax.swing.JButton onePlayer_Btn;
    private javax.swing.JButton songsong_Btn;
    // End of variables declaration//GEN-END:variables
}
